spring.application.name=ProjetoBarber

# Importar variaveis do .env 
spring.config.import=optional:file:.env

# Configuracaoes Banco de Dados - H2 em memoria
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Ativar console H2 na web para inspecao de dados
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Desativa provisoriamente MySQL
# spring.datasource.url=jdbc:mysql://localhost:3306/barber_db_java10x?createDatabaseIfNotExist=true&serverTimezone=UTC
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

# JPA e Hibernate (Para o H2 em desenvolvimento, deixamos o Spring criar as tabelas)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway (Desligado temporariamente pro H2)
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true
